# กำหนดค่าพื้นฐาน
title: "🌙 Midnight Space"
description: "Welcome to my dark & elegant corner"
theme: jekyll-theme-midnight

# เพิ่ม plugins ที่จำเป็น
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ตั้งค่าการแสดงผล
show_downloads: true
google_analytics: [Your Google Analytics ID]

# ข้อมูลผู้เขียน
author:
  name: Your Name
  email: your.email@example.com
